export enum ACTION_TYPES {
    SEARCH_NAME = 'SEARCH_NAME',
    ERROR = 'ERROR',
    LOADING = 'LOADING_START',
    GET_CHARACTERS = 'GET_CHARACTERS',
    GET_CHARACTER = 'GET_CHARACTER',
    PAGE_CHANGE = 'PAGE_CHANGE',
    PAGES_INFO = 'PAGES_INFO',
}
